---
version: "3.7"

services:

  simple-upload-server:
    build:
      context: ./go-simple-upload-server/
      dockerfile: Dockerfile
    image: local/simple-upload-server
    container_name: simple-upload-server
    restart: on-failure
    ports:
    - 0.0.0.0:8080:25478
    volumes:
    - /tmp:/var/root
    command: ["-token", "secret", "/var/root"]
