---
version: "3.7"

services:

  simple-upload-server:
    build:
      context: ./go-simple-upload-server/
      dockerfile: Dockerfile
    image: local/simple-upload-server
    container_name: simple-upload-server
    restart: on-failure
    ports:
    - 0.0.0.0:8080:25478
    volumes:
    - /tmp:/var/root
    command: ["-token", "secret", "/var/root"]

  simple-upload-server-sidecar:
    build:
      context: ./go-simple-upload-server/
      dockerfile: Dockerfile.sidecar
    image: local/simple-upload-server-sidecar
    container_name: simple-upload-server-sidecar
    restart: on-failure
    # w/ verbose output
    # command: ["-Qin", "-nvvvXi", "eth0", "port", "25478"]
    # w/o verbose output
    command: ["-Qin", "-nvvvi", "eth0", "port", "25478"]
    network_mode: "service:simple-upload-server"